import Head from "next/head";
import { Stack, Typography, Button } from "@mui/material";
import Navbar from "@/src/components/ui/Nav";
import colors from "@/src/utils/colors";
import CartCard from "@/src/components/ui/CartCard";
import { CartProps } from "@/src/interfaces";

const Cart = ({ cart }: CartProps) => {
  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack alignItems="center" spacing={2}>
        <Navbar />
        <Stack alignItems="center" spacing={2}>
          <Typography variant="h4" color={colors.white}>
            Cart
          </Typography>
          <Stack
            flexDirection={{ xs: "column", md: "row" }}
            justifyContent="space-between"
            gap={2}
          >
            {cart.map(({ title, description, image }) => {
              return (
                <CartCard
                  image={image}
                  title={title}
                  description={description}
                  key={title}
                />
              );
            })}
          </Stack>
          <Button variant="contained" fullWidth>
            BUY
          </Button>
        </Stack>
      </Stack>
    </>
  );
};

export default Cart;
